### ISSUE TITLE
Interest Rounding Error

### ISSUE THREAD

**Issue by ghost** [wearede/jasc#1]
The interest rate is rounded when parsed by parseInt, changing that to parseFloat correct the rounding error.

diff --git a/jquery.asc.js b/jquery.asc.js
index 6b84498..c753c8c 100644
--- a/jquery.asc.js
+++ b/jquery.asc.js
@@ -86,7 +86,7 @@

```
     function calculate() {
         var loanAmount    = parseInt($('#amortization-schedule-amount').val()),
```
-                loanInterest  = parseInt($('#amortization-schedule-interest').val()), // %
-                loanInterest  = parseFloat($('#amortization-schedule-interest').val()), // %
               loanDuration  = parseInt($('#amortization-schedule-duration').val()), // Month
               loanGrace     = parseInt($('#amortization-schedule-grace').val()), // Month
               loanInitMonth = parseInt($('#amortization-schedule-month').val()),

**Comment by ghost** [comment]
The markdown ate the patch.

hhttps://gist.github.com/nodoze313/e6833e097c6b8958bffa

**Comment by sandrodz** [comment]
Thank you! fixed.
