### ISSUE TITLE
Fixed Currency Decimals

### ISSUE THREAD

**Issue by ghost** [wearede/jasc#2]
The currency decimals are cut off due to how the round to 2 function returns the value, force to return as float with fixed length.

https://gist.github.com/nodoze313/f860558340a34462ba1a

**Comment by sandrodz** [comment]
Hey, thanks again. Updated file.

btw, did you use this plugin? It was a quick work for a friend. I'm happy if someone else found it useful.

**Comment by ghost** [comment]
Yes, I was able to use it, it is quite helpful, when it is complete I plan to email you with the details and testing copies.

**Comment by sandrodz** [comment]
Glad you found it useful.
